apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - peer-address: 10.1.0.3
      peer-asn: 207871
      my-asn: 207871
    - peer-address: 10.1.0.4
      peer-asn: 207871
      my-asn: 207871
    address-pools:
    - name: default
      protocol: bgp
      addresses:
      - 10.128.0.0/16
    - name: public-ips
      protocol: bgp
      addresses:
      - 45.151.166.0/24
      auto-assign: false
